apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
spec:
  maxReplicas: 5
  scaleTargetRef:
    kind: Deployment
    name: cart-deployment
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 512Mi