apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: internal
      port: 5672
      nodePort: 30072
    - name: external
      port: 15672
      nodePort: 30172