apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      name: todo
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: pinturavi/todo:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: SPRING_CONFIG_URL
              value: http://192.168.99.117:30088


